### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by annapng** [annapng/Blackjack-Project#71]

**Comment by rednblue97** [comment]
S/O to the TA's Karina ANNA JACOB KATIE DAVID 8+ HOURS SPENT ON JUST DEPLOYMENT OMG NEVER EVER AGAIN I CRY A MILLION TEARS AND FILL THE OCEAN. 6 MONTHS DOWN A LIFETIME TO GO!!!!!! GG'S Heroku maybe next time you'll get the better of us ;D

Anna finished the final build. We are done.
